from atmPy.general import measurement_site as ms

sites_list = [{'active': False,
  'Site Code': 'SGP',
  'lat': 37.841,
  'lon': -97.186,
  'Surface Type': 'Awaiting information',
  'name': 'Whitewater, KS (ABLE)',
  'alt': 0.0,
  'abbreviation': 'A1'},
 {'active': False,
  'Site Code': 'SGP',
  'lat': 37.627,
  'lon': -96.538,
  'Surface Type': 'Awaiting information',
  'name': 'Beaumont, KS (ABLE)',
  'alt': 0.0,
  'abbreviation': 'A2'},
 {'active': False,
  'Site Code': 'SGP',
  'lat': 37.626,
  'lon': -96.882,
  'Surface Type': 'Awaiting information',
  'name': 'Augusta, KS (ABLE)',
  'alt': 0.0,
  'abbreviation': 'A3'},
 {'active': False,
  'Site Code': 'SGP',
  'lat': 37.521,
  'lon': -96.855,
  'Surface Type': 'Awaiting information',
  'name': 'Smileyberg, KS (ABLE)',
  'alt': 0.0,
  'abbreviation': 'A4'},
 {'active': False,
  'Site Code': 'SGP',
  'lat': 37.273,
  'lon': -97.095,
  'Surface Type': 'Awaiting information',
  'name': 'Oxford, KS (ABLE)',
  'alt': 0.0,
  'abbreviation': 'A5'},
 {'active': False,
  'Site Code': 'SGP',
  'lat': 38.305,
  'lon': -97.301,
  'Surface Type': 'Awaiting information',
  'name': 'Hillsboro, KS (Boundary)',
  'alt': 447.0,
  'abbreviation': 'B1'},
 {'active': False,
  'Site Code': 'SGP',
  'lat': 36.071,
  'lon': -99.204,
  'Surface Type': 'Awaiting information',
  'name': 'Vici, OK (Boundary)',
  'alt': 622.0,
  'abbreviation': 'B4'},
 {'active': False,
  'Site Code': 'SGP',
  'lat': 35.688,
  'lon': -95.856,
  'Surface Type': 'Awaiting information',
  'name': 'Morris, OK (Boundary)',
  'alt': 217.0,
  'abbreviation': 'B5'},
 {'active': False,
  'Site Code': 'SGP',
  'lat': 34.985,
  'lon': -97.522,
  'Surface Type': 'Grass',
  'name': 'Purcell, OK (Boundary)',
  'alt': 344.0,
  'abbreviation': 'B6'},
 {'active': True,
  'Site Code': 'SGP',
  'lat': 36.605,
  'lon': -97.485,
  'Surface Type': 'Rangeland (Sandy)',
  'name': 'Central Facility, Lamont, OK',
  'alt': 318.0,
  'abbreviation': 'C1'},
 {'active': False,
  'Site Code': 'SGP',
  'lat': 38.202,
  'lon': -99.316,
  'Surface Type': 'Awaiting information',
  'name': 'Larned, KS (Extended)',
  'alt': 632.0,
  'abbreviation': 'E1'},
 {'active': False,
  'Site Code': 'SGP',
  'lat': 38.306,
  'lon': -97.301,
  'Surface Type': 'Awaiting information',
  'name': 'Hillsboro, KS (Extended)',
  'alt': 450.0,
  'abbreviation': 'E2'},
 {'active': False,
  'Site Code': 'SGP',
  'lat': 38.201,
  'lon': -95.597,
  'Surface Type': 'Awaiting information',
  'name': 'LeRoy, KS (Extended)',
  'alt': 338.0,
  'abbreviation': 'E3'},
 {'active': False,
  'Site Code': 'SGP',
  'lat': 37.953,
  'lon': -98.329,
  'Surface Type': 'Awaiting information',
  'name': 'Plevna, KS (Extended)',
  'alt': 513.0,
  'abbreviation': 'E4'},
 {'active': False,
  'Site Code': 'SGP',
  'lat': 38.114,
  'lon': -97.513,
  'Surface Type': 'Awaiting information',
  'name': 'Halstead, KS (Extended)',
  'alt': 440.0,
  'abbreviation': 'E5'},
 {'active': False,
  'Site Code': 'SGP',
  'lat': 37.842,
  'lon': -97.02,
  'Surface Type': 'Awaiting information',
  'name': 'Towanda, KS (Extended)',
  'alt': 409.0,
  'abbreviation': 'E6'},
 {'active': False,
  'Site Code': 'SGP',
  'lat': 37.383,
  'lon': -96.18,
  'Surface Type': 'Pasture',
  'name': 'Elk Falls, KS (Extended)',
  'alt': 283.0,
  'abbreviation': 'E7'},
 {'active': False,
  'Site Code': 'SGP',
  'lat': 37.333,
  'lon': -99.309,
  'Surface Type': 'Rangeland (Grazed)',
  'name': 'Coldwater, KS (Extended)',
  'alt': 664.0,
  'abbreviation': 'E8'},
 {'active': True,
  'Site Code': 'SGP',
  'lat': 37.133,
  'lon': -97.266,
  'Surface Type': 'Pasture',
  'name': 'Ashton, KS (Extended)',
  'alt': 386.0,
  'abbreviation': 'E9'},
 {'active': False,
  'Site Code': 'SGP',
  'lat': 37.068,
  'lon': -95.788,
  'Surface Type': 'Awaiting information',
  'name': 'Tyro, KS (Extended)',
  'alt': 248.0,
  'abbreviation': 'E10'},
 {'active': True,
  'Site Code': 'SGP',
  'lat': 36.881,
  'lon': -98.285,
  'Surface Type': 'Pasture',
  'name': 'Byron, OK (Extended)',
  'alt': 360.0,
  'abbreviation': 'E11'},
 {'active': True,
  'Site Code': 'SGP',
  'lat': 36.841,
  'lon': -96.427,
  'Surface Type': 'Native Prairie',
  'name': 'Pawhuska, OK (Extended)',
  'alt': 331.0,
  'abbreviation': 'E12'},
 {'active': True,
  'Site Code': 'SGP',
  'lat': 36.605,
  'lon': -97.485,
  'Surface Type': 'Pasture and Wheat',
  'name': 'Lamont, OK (Extended)',
  'alt': 318.0,
  'abbreviation': 'E13'},
 {'active': True,
  'Site Code': 'SGP',
  'lat': 36.607,
  'lon': -97.488,
  'Surface Type': 'Pasture and Wheat',
  'name': 'Lamont, OK (Extended, secondary)',
  'alt': 315.0,
  'abbreviation': 'E14'},
 {'active': True,
  'Site Code': 'SGP',
  'lat': 36.431,
  'lon': -98.284,
  'Surface Type': 'Pasture',
  'name': 'Ringwood, OK (Extended)',
  'alt': 418.0,
  'abbreviation': 'E15'},
 {'active': False,
  'Site Code': 'SGP',
  'lat': 36.061,
  'lon': -99.134,
  'Surface Type': 'Awaiting information',
  'name': 'Vici, OK (Extended)',
  'alt': 602.0,
  'abbreviation': 'E16'},
 {'active': False,
  'Site Code': 'SGP',
  'lat': 35.687,
  'lon': -95.856,
  'Surface Type': 'Pasture (Ungrazed)',
  'name': 'Morris, OK (Extended)',
  'alt': 217.0,
  'abbreviation': 'E18'},
 {'active': False,
  'Site Code': 'SGP',
  'lat': 35.557,
  'lon': -98.017,
  'Surface Type': 'Awaiting information',
  'name': 'El Reno, OK (Extended)',
  'alt': 421.0,
  'abbreviation': 'E19'},
 {'active': False,
  'Site Code': 'SGP',
  'lat': 35.564,
  'lon': -96.988,
  'Surface Type': 'Pasture',
  'name': 'Meeker, OK (Extended)',
  'alt': 309.0,
  'abbreviation': 'E20'},
 {'active': True,
  'Site Code': 'SGP',
  'lat': 35.615,
  'lon': -96.065,
  'Surface Type': 'Forest',
  'name': 'Okmulgee, OK (Extended)',
  'alt': 240.0,
  'abbreviation': 'E21'},
 {'active': False,
  'Site Code': 'SGP',
  'lat': 35.354,
  'lon': -98.977,
  'Surface Type': 'Awaiting information',
  'name': 'Cordell, OK (Extended)',
  'alt': 465.0,
  'abbreviation': 'E22'},
 {'active': False,
  'Site Code': 'SGP',
  'lat': 34.883,
  'lon': -98.205,
  'Surface Type': 'Awaiting information',
  'name': 'Cyril, OK (Extended)',
  'alt': 409.0,
  'abbreviation': 'E24'},
 {'active': False,
  'Site Code': 'SGP',
  'lat': 35.246,
  'lon': -96.736,
  'Surface Type': 'Pasture',
  'name': 'Seminole, OK (Extended)',
  'alt': 277.0,
  'abbreviation': 'E25'},
 {'active': False,
  'Site Code': 'SGP',
  'lat': 34.957,
  'lon': -98.076,
  'Surface Type': 'Pasture',
  'name': 'Cement, OK (Extended)',
  'alt': 400.0,
  'abbreviation': 'E26'},
 {'active': False,
  'Site Code': 'SGP',
  'lat': 35.269,
  'lon': -96.74,
  'Surface Type': 'Awaiting information',
  'name': 'Earlsboro, OK (Extended)',
  'alt': 300.0,
  'abbreviation': 'E27'},
 {'active': True,
  'Site Code': 'SGP',
  'lat': 37.1509,
  'lon': -98.362,
  'Surface Type': 'Pasture',
  'name': 'Anthony, KS (Extended)',
  'alt': 412.0,
  'abbreviation': 'E31'},
 {'active': True,
  'Site Code': 'SGP',
  'lat': 36.819,
  'lon': -97.8199,
  'Surface Type': 'Pasture',
  'name': 'Medford, OK (Extended)',
  'alt': 328.0,
  'abbreviation': 'E32'},
 {'active': True,
  'Site Code': 'SGP',
  'lat': 36.9255,
  'lon': -97.0817,
  'Surface Type': 'Cultivated field to south, site in grassy field',
  'name': 'Newkirk, OK (Extended)',
  'alt': 357.0,
  'abbreviation': 'E33'},
 {'active': True,
  'Site Code': 'SGP',
  'lat': 37.0694,
  'lon': -96.7606,
  'Surface Type': 'Pasture',
  'name': 'Maple City, KS (Extended)',
  'alt': 417.0,
  'abbreviation': 'E34'},
 {'active': True,
  'Site Code': 'SGP',
  'lat': 35.8615,
  'lon': -97.0695,
  'Surface Type': 'Pasture',
  'name': 'Tryon, OK (Extended)',
  'alt': 294.0,
  'abbreviation': 'E35'},
 {'active': True,
  'Site Code': 'SGP',
  'lat': 36.1166,
  'lon': -97.5112,
  'Surface Type': 'Pasture',
  'name': 'Marshall, OK (Extended)',
  'alt': 337.0,
  'abbreviation': 'E36'},
 {'active': True,
  'Site Code': 'SGP',
  'lat': 36.3106,
  'lon': -97.928,
  'Surface Type': 'Cultivated field to south, site in grass',
  'name': 'Waukomis, OK (Extended)',
  'alt': 379.0,
  'abbreviation': 'E37'},
 {'active': True,
  'Site Code': 'SGP',
  'lat': 35.8797,
  'lon': -98.1728,
  'Surface Type': 'Cultivated field to south, site in pasture',
  'name': 'Omega, OK (Extended)',
  'alt': 371.0,
  'abbreviation': 'E38'},
 {'active': True,
  'Site Code': 'SGP',
  'lat': 36.37354,
  'lon': -97.06905,
  'Surface Type': 'Cultivated field to south, site in pasture',
  'name': 'Morrison, OK (Extended)',
  'alt': 279.0,
  'abbreviation': 'E39'},
 {'active': True,
  'Site Code': 'SGP',
  'lat': 36.3199,
  'lon': -96.7652,
  'Surface Type': 'Pasture',
  'name': 'Pawnee, OK (Extended)',
  'alt': 247.0,
  'abbreviation': 'E40'},
 {'active': True,
  'Site Code': 'SGP',
  'lat': 36.87956,
  'lon': -97.08645,
  'Surface Type': 'Cultivated field to south, site in grassy field',
  'name': 'Peckham, OK (Extended)',
  'alt': 340.0,
  'abbreviation': 'E41'},
 {'active': True,
  'Site Code': 'SGP',
  'lat': 37.626,
  'lon': -96.538,
  'Surface Type': 'Awaiting information',
  'name': 'Beaumont, KS (Intermediate)',
  'alt': 478.0,
  'abbreviation': 'I1'},
 {'active': False,
  'Site Code': 'SGP',
  'lat': 37.28,
  'lon': -98.933,
  'Surface Type': 'Awaiting information',
  'name': 'Medicine Lodge, KS (Intermediate)',
  'alt': 616.0,
  'abbreviation': 'I2'},
 {'active': False,
  'Site Code': 'SGP',
  'lat': 35.551,
  'lon': -96.864,
  'Surface Type': 'Grass',
  'name': 'Meeker, OK (Intermediate)',
  'alt': 275.0,
  'abbreviation': 'I3'},
 {'active': True,
  'Site Code': 'SGP',
  'lat': 36.579,
  'lon': -97.3637,
  'Surface Type': 'Cultivated Field',
  'name': 'Billings, OK (Intermediate)',
  'alt': 330.0,
  'abbreviation': 'I4'},
 {'active': True,
  'Site Code': 'SGP',
  'lat': 36.4915,
  'lon': -97.5938,
  'Surface Type': 'Pasture',
  'name': 'Garber, OK (Intermediate)',
  'alt': 328.0,
  'abbreviation': 'I5'},
 {'active': True,
  'Site Code': 'SGP',
  'lat': 36.7673,
  'lon': -97.5481,
  'Surface Type': 'Cultivated Field',
  'name': 'Deer Creek, OK (Intermediate)',
  'alt': 341.0,
  'abbreviation': 'I6'},
 {'active': True,
  'Site Code': 'SGP',
  'lat': 36.7962,
  'lon': -97.4484,
  'Surface Type': 'Cultivated Field',
  'name': 'Nardin, OK (C-band radar site, Intermediate / Auxiliary)',
  'alt': 327.0,
  'abbreviation': 'I7'},
 {'active': True,
  'Site Code': 'SGP',
  'lat': 36.7095,
  'lon': -97.3876,
  'Surface Type': 'Pasture',
  'name': 'Tonkawa, OK (NE radar wind profiler site, Intermediate / Auxiliary)',
  'alt': 306.0,
  'abbreviation': 'I8'},
 {'active': True,
  'Site Code': 'SGP',
  'lat': 36.4762,
  'lon': -97.4217,
  'Surface Type': 'Pasture',
  'name': 'Billings, OK (SE radar wind profiler site, Intermediate / Auxiliary)',
  'alt': 291.0,
  'abbreviation': 'I9'},
 {'active': True,
  'Site Code': 'SGP',
  'lat': 36.6656,
  'lon': -97.6242,
  'Surface Type': 'Pasture (Ungrazed)',
  'name': 'Lamont, OK (NW radar wind profiler site, Intermediate / Auxiliary)',
  'alt': 312.0,
  'abbreviation': 'I10'}]

sgp_sites = ms.Network(sites_list, by_keys = ['name', 'abb'])